"""Generate public/data.js from the fidel.db database.

Produces a global `FidelData` object containing:
  - alphabet: array of { consonant, latin, vowels: [{ fidel, latin }] }
  - words: array of { latin, amharic, translation }

Run from the project root:
    python3 scripts/generate_data.py
"""
import json
import sqlite3
from pathlib import Path

ROOT = Path(__file__).parent.parent
DB_PATH = ROOT / 'fidel.db'
OUT_PATH = ROOT / 'public' / 'data.js'

VOWEL_SUFFIXES = ['a', 'u', 'i', 'a', 'e', 'e', 'o']
LATIN_FAMILIES = [
    'ha', 'la', 'ha', 'ma', 'sa', 'ra', 'sa', 'sha', 'qa', 'ba', 'ta', 'cha', 'ha', 'na', 'nya',
    'a', 'ka', 'kha', 'wa', 'a', 'za', 'zha', 'ya', 'da', 'ja', 'ga', 'ta', 'cha', 'pa', 'sa', 'sa', 'fa', 'pa', 'va'
]
CONSONANT_FAMILIES = [
    ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ'],
    ['ለ', 'ሉ', 'ሊ', 'ላ', 'ሌ', 'ል', 'ሎ'],
    ['ሐ', 'ሑ', 'ሒ', 'ሓ', 'ሔ', 'ሕ', 'ሖ'],
    ['መ', 'ሙ', 'ሚ', 'ማ', 'ሜ', 'ም', 'ሞ'],
    ['ሠ', 'ሡ', 'ሢ', 'ሣ', 'ሤ', 'ሥ', 'ሦ'],
    ['ረ', 'ሩ', 'ሪ', 'ራ', 'ሬ', 'ር', 'ሮ'],
    ['ሰ', 'ሱ', 'ሲ', 'ሳ', 'ሴ', 'ስ', 'ሶ'],
    ['ሸ', 'ሹ', 'ሺ', 'ሻ', 'ሼ', 'ሽ', 'ሾ'],
    ['ቀ', 'ቁ', 'ቂ', 'ቃ', 'ቄ', 'ቅ', 'ቆ'],
    ['በ', 'ቡ', 'ቢ', 'ባ', 'ቤ', 'ብ', 'ቦ'],
    ['ተ', 'ቱ', 'ቲ', 'ታ', 'ቴ', 'ት', 'ቶ'],
    ['ቸ', 'ቹ', 'ቺ', 'ቻ', 'ቼ', 'ች', 'ቾ'],
    ['ኀ', 'ኁ', 'ኂ', 'ኃ', 'ኄ', 'ኅ', 'ኆ'],
    ['ነ', 'ኑ', 'ኒ', 'ና', 'ኔ', 'ን', 'ኖ'],
    ['ኘ', 'ኙ', 'ኚ', 'ኛ', 'ኜ', 'ኝ', 'ኞ'],
    ['አ', 'ኡ', 'ኢ', 'ኣ', 'ኤ', 'እ', 'ኦ'],
    ['ከ', 'ኩ', 'ኪ', 'ካ', 'ኬ', 'ክ', 'ኮ'],
    ['ኸ', 'ኹ', 'ኺ', 'ኻ', 'ኼ', 'ኽ', 'ኾ'],
    ['ወ', 'ዉ', 'ዊ', 'ዋ', 'ዌ', 'ው', 'ዎ'],
    ['ዐ', 'ዑ', 'ዒ', 'ዓ', 'ዔ', 'ዕ', 'ዖ'],
    ['ዘ', 'ዙ', 'ዚ', 'ዛ', 'ዜ', 'ዝ', 'ዞ'],
    ['ዠ', 'ዡ', 'ዢ', 'ዣ', 'ዤ', 'ዥ', 'ዦ'],
    ['የ', 'ዩ', 'ዪ', 'ያ', 'ዬ', 'ይ', 'ዮ'],
    ['ደ', 'ዱ', 'ዲ', 'ዳ', 'ዴ', 'ድ', 'ዶ'],
    ['ጀ', 'ጁ', 'ጂ', 'ጃ', 'ጄ', 'ጅ', 'ጆ'],
    ['ገ', 'ጉ', 'ጊ', 'ጋ', 'ጌ', 'ግ', 'ጎ'],
    ['ጠ', 'ጡ', 'ጢ', 'ጣ', 'ጤ', 'ጥ', 'ጦ'],
    ['ጨ', 'ጩ', 'ጪ', 'ጫ', 'ጬ', 'ጭ', 'ጮ'],
    ['ጰ', 'ጱ', 'ጲ', 'ጳ', 'ጴ', 'ጵ', 'ጶ'],
    ['ጸ', 'ጹ', 'ጺ', 'ጻ', 'ጼ', 'ጽ', 'ጾ'],
    ['ፀ', 'ፁ', 'ፂ', 'ፃ', 'ፄ', 'ፅ', 'ፆ'],
    ['ፈ', 'ፉ', 'ፊ', 'ፋ', 'ፌ', 'ፍ', 'ፎ'],
    ['ፐ', 'ፑ', 'ፒ', 'ፓ', 'ፔ', 'ፕ', 'ፖ'],
    ['ቨ', 'ቩ', 'ቪ', 'ቫ', 'ቬ', 'ቭ', 'ቮ']
]


def build_alphabet():
    alphabet = []
    for family_index, family in enumerate(CONSONANT_FAMILIES):
        base_latin = LATIN_FAMILIES[family_index] or 'a'
        vowels = []
        for vowel_index, fidel in enumerate(family):
            vowel_suffix = VOWEL_SUFFIXES[vowel_index] if vowel_index < len(VOWEL_SUFFIXES) else ''
            latin = f'{base_latin}{vowel_suffix if vowel_suffix != "a" else ""}'
            vowels.append({'fidel': fidel, 'latin': latin})
        alphabet.append({'consonant': family[0], 'latin': base_latin, 'vowels': vowels})
    return alphabet


def build_words():
    conn = sqlite3.connect(str(DB_PATH))
    rows = conn.execute('SELECT latin, amharic, translation FROM words').fetchall()
    conn.close()
    words = []
    for latin, amharic, translation in rows:
        words.append({'latin': latin, 'amharic': amharic, 'translation': translation or ''})
    return words


def main():
    alphabet = build_alphabet()
    words = build_words()
    payload = {
        'alphabet': alphabet,
        'words': words,
    }
    out = f'// Auto-generated by scripts/generate_data.py. Do not edit manually.\n'
    out += 'window.FidelData = '
    out += json.dumps(payload, ensure_ascii=False)
    out += ';\n'
    OUT_PATH.write_text(out, encoding='utf-8')
    print(f'Wrote {OUT_PATH} ({len(words)} words, {len(alphabet)} families)')


if __name__ == '__main__':
    main()
